from __future__ import annotations

from datetime import datetime
from typing import Protocol

from polaris_pr_intel.models import DailyReport, IssueSignal, IssueSnapshot, PRSummary, PullRequestSnapshot, ReviewSignal


class Repository(Protocol):
    prs: dict[int, PullRequestSnapshot]
    issues: dict[int, IssueSnapshot]
    pr_summaries: dict[int, PRSummary]
    review_signals: dict[int, ReviewSignal]
    issue_signals: dict[int, IssueSignal]
    daily_reports: list[DailyReport]
    last_sync_at: datetime | None

    def upsert_pr(self, pr: PullRequestSnapshot) -> None: ...
    def upsert_issue(self, issue: IssueSnapshot) -> None: ...
    def save_pr_summary(self, summary: PRSummary) -> None: ...
    def save_review_signal(self, signal: ReviewSignal) -> None: ...
    def save_issue_signal(self, signal: IssueSignal) -> None: ...
    def save_daily_report(self, report: DailyReport) -> None: ...
    def latest_daily_report(self) -> DailyReport | None: ...
    def list_daily_reports(self, limit: int = 30, offset: int = 0) -> list[DailyReport]: ...
    def has_processed_event(self, delivery_id: str) -> bool: ...
    def mark_processed_event(self, delivery_id: str) -> None: ...
