from __future__ import annotations

from datetime import datetime
from typing import Protocol

from polaris_pr_intel.models import (
    AnalysisRun,
    DailyReport,
    IssueSignal,
    IssueSnapshot,
    PRReviewReport,
    PRSummary,
    PullRequestSnapshot,
    ReviewSignal,
)


class Repository(Protocol):
    prs: dict[int, PullRequestSnapshot]
    issues: dict[int, IssueSnapshot]
    pr_summaries: dict[int, PRSummary]
    review_signals: dict[int, ReviewSignal]
    issue_signals: dict[int, IssueSignal]
    pr_review_reports: dict[int, PRReviewReport]
    daily_reports: list[DailyReport]
    analysis_runs: list[AnalysisRun]
    last_sync_at: datetime | None

    def upsert_pr(self, pr: PullRequestSnapshot) -> None: ...
    def upsert_issue(self, issue: IssueSnapshot) -> None: ...
    def save_pr_summary(self, summary: PRSummary) -> None: ...
    def save_review_signal(self, signal: ReviewSignal) -> None: ...
    def save_issue_signal(self, signal: IssueSignal) -> None: ...
    def save_pr_review_report(self, report: PRReviewReport) -> None: ...
    def save_daily_report(self, report: DailyReport) -> None: ...
    def save_analysis_run(self, run: AnalysisRun) -> None: ...
    def latest_daily_report(self) -> DailyReport | None: ...
    def list_daily_reports(self, limit: int = 30, offset: int = 0) -> list[DailyReport]: ...
    def latest_analysis_run(self) -> AnalysisRun | None: ...
    def list_analysis_runs(self, limit: int = 30, offset: int = 0) -> list[AnalysisRun]: ...
    def latest_pr_review_report(self, pr_number: int) -> PRReviewReport | None: ...
    def top_pr_review_reports(self, limit: int = 20) -> list[PRReviewReport]: ...
    def has_processed_event(self, delivery_id: str) -> bool: ...
    def mark_processed_event(self, delivery_id: str) -> None: ...
